name: Fly Deploy
on:
  push:
    branches:
       - master # change to main if needed
jobs:
  deploy:
  name: chatbot.py
  runs-on: ubuntu-latest
  concurrency: deploy-group # optional: ensure only one action runs at a time
  steps:
  - uses: actions/checkout@v3
  - uses: superfly/flyctl-actions/setup-flyctl@master
  - run: flyctl deploy --remote-only
    env:
      FLY_API_TOKEN: ${{FlyV1 fm2_lJPECAAAAAAACGnKxBDctjW43YkrpWj3lP2lhacYwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAA9o2R8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDyUBwHsSgvt3uMfI05VSr1uYldM4ZiqlFQpiQjD9jzknMAF8SY8eFab747eG+i3iphQhZ7YFsQphd6EC9jETuY1zA2MJc3IEFy4M75WQnnHf6+/kfGeFIrhdv650/niciJZ22JDwqHbXjto0rTMvnzaOVtIQJLF+tjyjPJi/xhySlfL2BvcHkqpwKMG4g2SlAORgc4Aan2hHwWRgqdidWlsZGVyH6J3Zx8BxCASAUHrtet4lmWsVOWEYC6q2eDEDMLMYoEH0A7As9pRcw==,fm2_lJPETuY1zA2MJc3IEFy4M75WQnnHf6+/kfGeFIrhdv650/niciJZ22JDwqHbXjto0rTMvnzaOVtIQJLF+tjyjPJi/xhySlfL2BvcHkqpwKMG4sQQFzTBUsCZn/Y0Oy5SCnXjdsO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5n2jKKzwAAAAE+bciYF84ADtCrCpHOAA7QqwzEENKCGGM+v+Ul+brWfoGGQuPEIDNre9cN5eOSyXt1h7W/d+K6K+51ICM13hZRw/58y6Ho}}
