name: Fly Deploy

on:
  push:
    branches:
      - main  # 如果使用 main 分支，改为 [main]

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency:  # 并发控制（可选）
      group: deploy-group
      cancel-in-progress: true  # 取消正在进行的旧任务

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4  # 升级到最新版本

      # 2. 配置 Flyctl 工具
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v2  # 使用稳定版本

      # 3. 执行部署命令
      - name: Deploy Application
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # 确保已在仓库 Secrets 中添加此 Token
